[package]
name = "cref"
version = "0.1.0"
authors = ["Kentaro Takiguchi <takiguchi0817@gmail.com>"]

[[bin]]
name = "cref"

[dependencies]
rustc-serialize = "*"
docopt = "*"
docopt_macros = "*"
rust-sqlite = "*"
time = "*"
hyper = "*"
env_logger = "*"
log = "*"
term = "*"
rustbox = "*"
regex = "*"
